<?xml version="1.0"?>
<package format="3">
  <name>csv_obstacle</name>
  <version>0.0.1</version>
  <description>Publish obstacles from CSV</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <!-- ament_python 빌드 선언 -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- 런타임 의존성 (필요한 것만 유지/추가) -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
