slam_toolbox:
  ros__parameters:
    # Frame IDs - F1TENTH에 맞게 설정
    base_frame: base_link
    odom_frame: odom  
    map_frame: map
    scan_topic: /scan
    
    # Basic settings
    use_sim_time: false
    mode: mapping
    
    # SLAM parameters
    resolution: 0.05
    map_update_interval: 0.5
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    
    # Loop closure
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    
    # Other settings
    debug_logging: false
    enable_interactive_mode: true
