slam_toolbox:
  ros__parameters:
    # Frame IDs - F1TENTH에 맞게 설정
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    scan_topic: /scan

    # Basic settings
    use_sim_time: false
    mode: mapping

    # SLAM parameters
    resolution: 0.05
    map_update_interval: 1.0
    minimum_travel_distance: 0.15
    minimum_travel_heading: 0.15

    # === 강화된 루프 클로저 설정 ===
    do_loop_closing: true

    # 루프 클로저 검색 거리 (F1TENTH 실내 트랙 환경에 적합)
    loop_search_maximum_distance: 5.0
    loop_search_space_dimension: 10.0

    # 루프 매칭 파라미터 (F1TENTH 고속 주행 고려)
    loop_match_minimum_chain_size: 8
    loop_match_minimum_response_coarse: 0.3
    loop_match_minimum_response_fine: 0.4
    loop_match_maximum_variance_coarse: 3.0

    # 최적화 빈도 (트랙에서 빠른 루프 완주 고려)
    optimize_every_n_nodes: 10

    # 상관관계 검색 설정 (정밀한 매칭을 위해)
    correlation_search_space_dimension: 0.8
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # 스캔 매칭 향상
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_size: 15
    scan_buffer_maximum_scan_distance: 8.0

    # F1TENTH 레이싱카에 적합한 링크 매칭
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 2.0

    # 각도/거리 페널티 (소형 레이싱카에 맞게 조정)
    minimum_angle_penalty: 0.85
    minimum_distance_penalty: 0.4
    use_response_expansion: true

    # === 추가 성능 최적화 설정 ===
    # 라이다 설정 - 자유공간 생성 최적화
    max_laser_range: 10.0
    minimum_laser_range: 0.1
    
    # 자유공간 마킹 향상
    mark_threshold: 0.0
    update_factor_free: 0.4
    update_factor_occupied: 0.9

    # 스캔 품질 향상
    use_scan_barycenter: true

    # 메모리 관리
    scan_buffer_maximum_scan_distance: 10.0

    # 매칭 품질 향상
    coarse_search_angle_offset: 0.349
    fine_search_angle_offset: 0.00349

    # 맵 품질 설정 - 자유공간 생성 향상
    occupied_threshold: 0.65
    free_threshold: 0.25
    
    # 맵 업데이트 설정
    map_update_interval: 0.5
    
    # 자유공간 생성을 위한 추가 설정
    minimum_beam_count: 5
    transform_timeout: 0.2

    # Other settings
    debug_logging: false
    enable_interactive_mode: true

    # 차량 크기 설정 (0.5m x 0.3m 직사각형)
    footprint: "[[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]"
    robot_radius: 0.3 